version: "3"

# Containers we are going to run
services:
  # Our server.
  server:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: server
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: rocketpay_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    networks:
      - nlw-network
    volumes:
      - ./server:/app
      - build:/app/rocketpay/_build
    tty: true
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocketpay_dev
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - nlw-network

volumes:
  build: {}

# Common network to 'app' and 'db' services
networks:
  nlw-network:
    driver: bridge
